name: RustLinux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Config Env
        run: rustup install nightly && rustup default nightly
      - name: Build
        run: cd gdrust && cargo build --all
      - name: Build Release
        run: cd gdrust && cargo build --all --release
      - name: Run tests Debug
        run: cd gdrust && cargo test --all
      - name: Run tests Release
        run: cd gdrust && cargo test --all --release
      - name: Install Godot
        run: wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip && unzip Godot_v4.2.2-stable_linux.x86_64.zip && mv ./Godot_v4.2.2-stable_linux.x86_64 ./godot
      - name: Godot Test
        run: cd script && python godot_test.py
