name: RustfmtCheck

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Config Env
        run: rustup install nightly && rustup default nightly && rustup component add rustfmt
      - name: Check Fmt
        run: cd gdrust && cargo fmt -- --check
