name: RustMacos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd gdrust && cargo build --all
      - name: Build Release
        run: cargo build --all --release
      - name: Run tests Debug
        run: cargo test --all
      - name: Run tests Release
        run: cargo test --all --release

